import { Tree, formatFiles } from '@nx/devkit';
import { CustomLibGeneratorSchema } from './schema';
import { prompt } from 'enquirer';

export default async function (tree: Tree, options: CustomLibGeneratorSchema) {
  if (!options.name || options.name.trim() === '') {
    const response = await prompt<{ libName: string }>([
      {
        type: 'input',
        name: 'libName',
        message: '🐸 How should we name your library?',
        validate: (value) => (value.trim() ? true : '👉 You must provide a name!'),
      },
    ]);
    options.name = response.libName;
  }

  if (options.build === undefined) {
    const response = await prompt<{ build: boolean }>([
      {
        type: 'confirm',
        name: 'build',
        message: '🐸 Add build target?',
      },
    ]);
    options.build = response.build;
  }

  if (options.unitTest === undefined) {
    const response = await prompt<{ unitTest: boolean }>([
      {
        type: 'confirm',
        name: 'unitTest',
        message: '🐸 Add unit testing setup?',
      },
    ]);
    options.unitTest = response.unitTest;
  }

  const libName = sanitizeLibName(options.name);
  const libRoot = `libs/${libName}`;

  tree.write(
    `${libRoot}/src/index.ts`,
    `export const hello = () => console.log('Hello from ${libName}!');`,
  );
  tree.write(
    `${libRoot}/README.md`,
    `# ${libName}\n\nGenerated by \`company-generators:custom-lib\`.`,
  );

  const projectJson: any = {
    name: libName,
    $schema: '../../node_modules/nx/schemas/project-schema.json',
    sourceRoot: `${libRoot}/src`,
    projectType: 'library',
    targets: {},
    tags: [],
  };

  if (options.build) {
    projectJson.targets.build = {
      executor: 'nx:run-commands',
      options: {
        command: "echo 'Building ${libName}...'",
      },
    };
  }

  if (options.unitTest) {
    projectJson.targets.test = {
      executor: 'nx:run-commands',
      options: {
        command: "echo 'Running tests for ${libName}...'",
      },
    };
  }

  tree.write(`${libRoot}/project.json`, JSON.stringify(projectJson, null, 2));

  await formatFiles(tree);
}

function sanitizeLibName(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/--+/g, '-')
    .replace(/^-+|-+$/g, '');
}
